### ISSUE TITLE
Failed to validate purchase on some receipt data

### ISSUE THREAD

**Issue by superandrew213** [voltrue2/in-app-purchase#101]
I have implemented `in-app-purchase` in my application and it works quite good. However I keep getting some `failed to validate purchase` errors now and then. The error happens for both iOS & Android

### Android

Error causing receipt
```
{
  data: '{
    "orderId":"123123132123123.12312312312312312312313",
    "packageName":"aaa.bbb.ccc",
    "productId":"aaa.bbb.ccc.sub",
    "purchaseTime":1499506382078,
    "purchaseState":0,
    "developerPayload":"xxxxx",
    "purchaseToken":"ugujegkxtfnvqaqqclnhpfrw"
  }',
  signature: 'xxxxx'
}
```

My proper functioning receipts (which look more like the ones in the tests):
```
{
  data: '{
    "orderId":"GPA.xxxx-xxxx-xxxx-xxxx",
    "packageName":"aaa.bbb.ccc",
    "productId":"aaa.bbb.ccc.sub",
    "purchaseTime":1498002890901,
    "purchaseState":0,
    "developerPayload":"xxxxxx",
    "purchaseToken":"edgcacfhmkpekcilnihgdjkb.AO-J1OxnZr_-c4xGioV-wbb9YI4w7gtRzY87CRLsa6CrHuP_nF97WNzHaBjbqCyZeYYf_sZByLD1DKxkMOFlpIsiOJnSeHxu5XIwa303DbJwFQ7Lo-sM6dgY4-4DCEqk61C9qgUx0GsLaOMZJF0zMC0mRS9K8Z2P3-uSDQpUv0qorTGt7xQC42s",
    "autoRenewing":true
  }',
  signature: 'xxxxxx'
}
```
Differences I can see are the `orderId`, `purchaseToken` and no `autoRenewing`. 

### iOS

Base64 decoded data

```
{
    pod = 50;
    "purchase-info" = ewp9;
    signature = "xxxx";
    "signing-status" = 0;
}
```
Shouldn't `ewp9` be a string? Shouldn't the decoded receipt data be binary?

Anyone else has come across this before? Is this a receipt faking attempt?

**Comment by jshanman** [comment]
For google play orders, I see the same problem.  Orders with orderId "n.n" format are failing validation but orders with the other format work as expected.  The failing orders represent about 40% of our orders so I need to get this figured out soon. Anyone else see this?

**Comment by voltrue2** [comment]
Hello,

@superandrew213 For iOS, the decoded receipt is actually an object.
As for `purchase-info` the data type of the property should be a string.
Would you be able to give me the whole decoded receipt data? (you can blot out private infomation, of cource).

@jshanman It is really curious that receipts with orderId "n.n" format fail to validate. I will need to look into this. Thank you for reporting this also.

Cheers!

**Comment by voltrue2** [comment]
@jshanman So orderId format "n.n" is the latest format of order ID after 5th Dec 2012 according to Google.
Link here: https://developer.android.com/google/play/billing/billing_admin.html#orderId

**Comment by superandrew213** [comment]
@voltrue2 that is the whole decoded receipt data (signature replaced with xxxx). Do you need signature too?

Just to confirm, this is the new order number format according to Google:
```
"orderId" : "GPA.1234-5678-9012-34567"
```

And this was the one before 5th Dec 2012:
```
"orderId" : "556515565155651"
```

I'm getting this:
```
"orderId":"123123132123123.12312312312312312312313",
```

This `5565155651556511` is the same length as this `123123132123123`.

**Comment by superandrew213** [comment]
Some other discussions about the iOS part:
https://stackoverflow.com/questions/30745267/apple-in-app-purchase-receipt-in-wrong-format
https://forums.developer.apple.com/thread/4082

**Comment by jshanman** [comment]
@voltrue2 I'm seeing the same thing @superandrew213 mentioned.  my comment with "n.n" was misleading.

We have an android client sending the receipts directly to our backend and I am recording them, then validating them. About 40% are coming through in example #1 and are NOT validating. The remaining 60% are coming in as example #2 and ARE validating properly.  I've changed all the purchase tokens and orderId's and removed the signature to protect the innocent.

Example #1
```{"data":"{\"purchaseToken\":\"tilxftiixprxpiycoaaaaaaa\",\"developerPayload\":\"\",\"packageName\":\"com.my.app\",\"purchaseState\":0,\"orderId\":\"1299396727903350000.6888410186550000\",\"purchaseTime\":1500651020000,\"productId\":\"my_product\"}","signature":"..."}```

Example #2
```{“data”:“{\“orderId\“:\“GPA.1111-1111-1111-11111\“,\“packageName\“:\“com.my.app\“,\“productId\“:\“my_product\“,\“purchaseTime\“:1500544580000,\“purchaseState\“:0,\“purchaseToken\“:\“focbnnhmnlocfelamaaaaaaa.AO-J1Oz7sG9RUvuxFQVPbaaaaa-NbLpW5hF86siKjIvCu69yqPB6HIW8GfLChdK0J0dVfm2aaaaaa-QLoy6SHwqmjF4Q99tWIXV43RcPBK_ZvUDRmtJarMkTJ5ZKBDZqttZHna0A0a0A0\“,\“autoRenewing\“:true}“,”signature”:“...“}```

I'll do a bit more digging today to see exactly where in this library the validation is failing.

**Comment by jshanman** [comment]
It is failing in google.js at 
```   
      valid = validater.verify(pkey, receipt.signature, 'base64');
```
and gets to
```
	// failed to validate
	cb(new Error('failed to validate purchase'));
```

I should note that I've found a few other people posting about the same problem recently, but no answers yet.

https://stackoverflow.com/questions/45132122/in-app-billing-purchases-not-on-google-play-weird-receipts
https://stackoverflow.com/questions/45003996/android-billing-order-id

**Comment by voltrue2** [comment]
Hello

This issue maybe related to this. I have implemented the solution.
Please have a look here: https://github.com/voltrue2/in-app-purchase/issues/113

**Comment by superandrew213** [comment]
@voltrue2 it's still not working for me. Android is still failing validation. Thank you for the update though. It might have fixed some other fails.

@jshanman have you tested the new version?

I also found a receipt with `"orderId":"GPA.xxxx-xxxx-xxxx-xxxx"` failing validation. But most are still `"orderId":"123123132123123.12312312312312312312313"`

Another weird thing is that I am only validating subscriptions but get receipt data without `autoRenewing`. Should `autoRenewing` be always be there for subscriptions?

```
{
  data: '{
    "orderId":"123123132123123.12312312312312312312313",
    "packageName":"aaa.bbb.ccc",
    "productId":"aaa.bbb.ccc.sub",
    "purchaseTime":1499506382078,
    "purchaseState":0,
    "developerPayload":"xxxxx",
    "purchaseToken":"ugujegkxtfnvqaqqclnhpfrw"
  }',
  signature: 'xxxxx'
}
```

**Comment by voltrue2** [comment]
@superandrew213 Thanks for the feedback.
I assumed `autoRenewing` to be always present for all subscription receipts.
The latest version checks for that field to identify whether it is a subscription or not, so if your receipt does not contain `autoRenewing`, the module thinks it is a regular consumable.
I believe that is the reason for failing to validate.
Let me look into this `autoRenewing` field.

Cheers

**Comment by voltrue2** [comment]
@superandrew213 
I made some changes to `develop` branch.
The commit is this: aa68b3227cb9605cb7705c697b38d9833953931c
Since I cannot test against your receipt, you would mind testing the new code against your receipt that is failing with `verbose: true`?
Thank you for your help!

Cheers

**Comment by superandrew213** [comment]
@voltrue2 please see screenshots with logs. There are two log outputs for both different orderIds: `xxxxx.xxxxxx` & `GPA.xxxx-xxxx-xxxx-xxxx`. Also orderIds `GPA.xxxx-xxxx-xxxx-xxxx` that fail validation can't be found in the Order Management dashboard.



Thank you for looking into this!
`xxxxx.xxxxxx`
<img width="902" alt="screen shot 2017-08-04 at 12 34 05 pm" src="https://user-images.githubusercontent.com/13059204/28952515-04a2d700-7915-11e7-99c9-3aec71d7de33.png">



`GPA.xxxx-xxxx-xxxx-xxxx`
<img width="902" alt="screen shot 2017-08-04 at 12 50 40 pm" src="https://user-images.githubusercontent.com/13059204/28952517-06afc4c2-7915-11e7-9aa2-8a5eb5263e91.png">

**Comment by jshanman** [comment]
I believe the "123.456" format order id's and the short tokens are from fraudulent purchase attempts.  See https://stackoverflow.com/questions/31402531/google-iap-returns-short-purchase-token-for-verification

We are trying to find a way to validate this assumption with a google contact or through testing. I'll update this page if we know more. If this is the case, then this library is working as intended.

**Comment by superandrew213** [comment]
I agree. In app purchase hacking apps that haven't been updated by their authors must still be using older order ids to fake receipts.

Hacking apps that have been updated are using the new order ids. These ids don't exist when I try to look them up. They are also being correctly caught by 'in-app-purchase'.

**Comment by voltrue2** [comment]
@jshanman @superandrew213 
Thank you for the information. I will also look into this issue.

Cheers

**Comment by ntlzz93** [comment]
the same issue with me

**Comment by voltrue2** [comment]
@ntlzz93 Please read the earlier comments on this thread.
these receipts seem to be hacking attempts.

Cheers

**Comment by voltrue2** [comment]
Closing
