### ISSUE TITLE
IAP.getPurchaseData ignoring latest purchase

### ISSUE THREAD

**Issue by nickkuh** [voltrue2/in-app-purchase#49]
Hey Guys

Thanks for this great module.

My app implements Apple autorenewable subscriptions. But now some of the subscriptions have renewed (the initial subscription being a monthly subscription just over a month ago) the IAP node module isn't recognising this and treats repeat subscriptions as expired.

I can see the reason for the bug in the source code too:

https://github.com/voltrue2/in-app-purchase/blob/develop/lib/apple.js#L190

REC_KEYS.IN_APP references the array named 'in_app' but for some reason Apple's auto-renewable receipts only include the new purchases within an array named 'latest_receipt_info'.

Here's an example:

```
in_app: 
      [ { quantity: '1',
          product_id: 'blah.blah.blah',
          transaction_id: '210000259386802',
          original_transaction_id: '210000259386802',
          purchase_date: '2016-04-14 16:03:33 Etc/GMT',
          purchase_date_ms: '1460649813000',
          purchase_date_pst: '2016-04-14 09:03:33 America/Los_Angeles',
          original_purchase_date: '2016-04-14 16:03:34 Etc/GMT',
          original_purchase_date_ms: '1460649814000',
          original_purchase_date_pst: '2016-04-14 09:03:34 America/Los_Angeles',
          expires_date: '2016-05-14 16:03:33 Etc/GMT',
          expires_date_ms: '1463241813000',
          expires_date_pst: '2016-05-14 09:03:33 America/Los_Angeles',
          web_order_line_item_id: '210000038560504',
          is_trial_period: 'false' } ] },
  latest_receipt_info: 
   [ { quantity: '1',
       product_id: 'blah.blah.blah',
       transaction_id: '210000259386802',
       original_transaction_id: '210000259386802',
       purchase_date: '2016-04-14 16:03:33 Etc/GMT',
       purchase_date_ms: '1460649813982',
       purchase_date_pst: '2016-04-14 09:03:33 America/Los_Angeles',
       original_purchase_date: '2016-04-14 16:03:34 Etc/GMT',
       original_purchase_date_ms: '1460649814000',
       original_purchase_date_pst: '2016-04-14 09:03:34 America/Los_Angeles',
       expires_date: '2016-05-14 16:03:33 Etc/GMT',
       expires_date_ms: '1463241813982',
       expires_date_pst: '2016-05-14 09:03:33 America/Los_Angeles',
       web_order_line_item_id: '210000038560504',
       is_trial_period: 'false' },
     { quantity: '1',
       product_id: 'blah.blah.blah',
       transaction_id: '210000265773203',
       original_transaction_id: '210000259386802',
       purchase_date: '2016-05-14 16:03:33 Etc/GMT',
       purchase_date_ms: '1463241813000',
       purchase_date_pst: '2016-05-14 09:03:33 America/Los_Angeles',
       original_purchase_date: '2016-05-14 10:03:37 Etc/GMT',
       original_purchase_date_ms: '1463220217552',
       original_purchase_date_pst: '2016-05-14 03:03:37 America/Los_Angeles',
       expires_date: '2016-06-14 16:03:33 Etc/GMT',
       expires_date_ms: '1465920213000',
       expires_date_pst: '2016-06-14 09:03:33 America/Los_Angeles',
       web_order_line_item_id: '210000038560503',
       is_trial_period: 'false' } ],
```

As you can see above this customer's second subscription payment completed for another month's use of my app. However, calling

`IAP.getPurchaseData(appleRes);`

Results in parsing the  'in_app' array and not the 'latest_receipt_info' array that contains the latest purchase. 

Is this a change in Apple's receipt format?

Cheers

Nick

**Comment by voltrue2** [comment]
Hello Nick,

Thank you for reaching out.

I will look into this right away.
The subscription receipt format might have changed as you pointed out.

Best Regards

**Comment by voltrue2** [comment]
Hello

I have updated the module to include 'latest_receipt_info' array to be
parsed by .getPurchaseData().

Commit:
https://github.com/voltrue2/in-app-purchase/commit/2e86b170b8d506639aa00c64965b0084ce9da0cb
npm version: in-app-purchase@1.1.3

Thank you again for reaching out.

It would be really awesome if you could let me know if the update solves
your problem or not.

Best Regards

**Comment by nickkuh** [comment]
Hi @voltrue2 

Thanks for looking into. I just tested and the problem isn't quite resolved. Two modifications will fix it:

'latest_receipt_info' is actually at the same level in the data structure as 'receipt'. So the code needs to look one level higher in the data. e.g.:

> purchase[REC_KEYS.LRI]

And, it would be even better if the code worked like this:

> if (purchase[REC_KEYS.LRI]) {
> 			list = purchase[REC_KEYS.LRI] || [];
> 		}

Rather than concatenating as you end up with a duplicate transaction object from the receipt and latest_receipt_info arrays.

If you change I'll retest.

Nick

**Comment by voltrue2** [comment]
Hello Nick

Thank you for testing it and pointing out the issue.
I'll get on it ASAP.

Best Regards

**Comment by voltrue2** [comment]
Hello

I pushed the fix to the problem with parsing latest_purchase_info.

There is a one difference from what you suggested in the fix.

I decided to parse items in in_app array along with what's in latest_receipt_info array and check for duplicates.
The reason for that is to keep the returned results the same as it was with the addition of the items from latest_receipt_info.

If you could retest, it would be really great!

Best Regards

**Comment by nickkuh** [comment]
Still not working. Because all purchase items share the same PRODUCT_ID. You should check for dupes on the TRANSACTION_ID

**Comment by voltrue2** [comment]
Hello Nick,

Right. It was my bad. I will fix it.

Best

**Comment by voltrue2** [comment]
Hello

I also noticed that I should be checking against original_transaction_id instead for duplicates as transaction_id will be different when subscription is renewed.
So the parser checks and keeps the most recent original transaction receipt now.

I pushed the updated version to git.

Thank you again for the help.

Best

**Comment by nickkuh** [comment]
Perfect @voltrue2 - thanks for sorting!
