### ISSUE TITLE
Something Seriously Wrong when using Keys in String

### ISSUE THREAD

**Issue by anilalgoworks** [voltrue2/in-app-purchase#7]
I am trying to use the module with  Keys Passing Directly in Strings for google like 

iap.config({
    publicKeyStrSandBox: publicKeySandboxString,
    publickKeyStrLive: publicKeyLiveString
});

But it always gives me error Missing Public Key. Please Check and Debug if you can asap as i need to use it in my project.

**Comment by voltrue2** [comment]
Hi, 

It looks like I have a typo in my README file and also my last npm publish had gone wrong it seems.
Thank you very much for catching and reporting this. I published the fixed version on npm.
The version should be 0.4.6

**Comment by anilalgoworks** [comment]
Still Getting the Same Error in 0.4.6.
Following is the code chunk

describe.only('iap', function () {
    it('Can validate google in-app-purchase with public key as string', function (done) {
        var iap = require('in-app-purchase');
        iap.config({
            publicKeyStrSandBox  : appConstants.env.GOOGLE_IAB_PUBLICKEY,
            publicKeyStrLive : appConstants.env.GOOGLE_IAB_PUBLICKEY
        });
        iap.setup(function (error) {
            assert.equal(error, undefined);
            iap.validate(iap.GOOGLE, { data: 'fake-receipt', signature: 'fake' }, function (error, response) {
                assert(error);
                assert.equal(iap.isValidated(response), false);
                done();
            });
        });
    });
});

**Comment by anilalgoworks** [comment]
describe.only('iap', function () {
    it('Can validate google in-app-purchase with public key as string', function (done) {
        var iap = require('in-app-purchase');
        iap.config({
            publicKeyStrSandBox  : appConstants.env.GOOGLE_IAB_PUBLICKEY,
            publicKeyStrLive : appConstants.env.GOOGLE_IAB_PUBLICKEY
        });
        iap.setup(function (error) {
            assert.equal(error, undefined);
            iap.validate(iap.GOOGLE, { data: 'fake-receipt', signature: 'fake' }, function (error, response) {
                assert(error);
                assert.equal(iap.isValidated(response), false);
                done();
            });
        });
    });
});

**Comment by voltrue2** [comment]
hmmm interesting. I ran `make google-test` and it worked. Let me have a look at it again.
Thanks for following up on this.

**Comment by anilalgoworks** [comment]
the test runs fine .. because it is supposed to return isValidated false in this case... but i want response from google but here our code itself returns error "Missing Public Key"

**Comment by voltrue2** [comment]
assert.equal(error, undefined); part fails right?

**Comment by anilalgoworks** [comment]
just checkout what assert(error); returns in above Scenario .

**Comment by voltrue2** [comment]
i assume these have values right?

appConstants.env.GOOGLE_IAB_PUBLICKEY,
appConstants.env.GOOGLE_IAB_PUBLICKEY

**Comment by anilalgoworks** [comment]
yupp i have my 64 bit public license key  value in both of them like MIIBIjANBg........................QAB

**Comment by anilalgoworks** [comment]
as far as i can see your isValidConfigKey method in google.js validates configKey having google word used in them.
	return key.match(/^google/);
Both keys doesnt contain the same i.e. publicKeyStrSandBox,publicKeyStrLive
so it return config as null for them.

**Comment by anilalgoworks** [comment]
any update?

**Comment by voltrue2** [comment]
hey sorry. i had to deal with lots of stuff. i may be able to look at it later.
by the way, if you are planning on using env varriable, you can use it without using string.

**Comment by voltrue2** [comment]
Hi sorry it took me long to actually make the time to properly look into this.

Now I know what is going wrong. It's the documentation that is wrong (my bad).

basically it needs to be googlePublicKeyStrSanbox and googlePublicKeyStrLive.

and the reason my unit tests work is because i am using those property names.

Would you please give it a try?

I will fix READ me in the meantime.

Thanks

**Comment by voltrue2** [comment]
actually i will make it so that it will work with either googlePublicKeyStrXXX or publicKeyStrXXXX

**Comment by voltrue2** [comment]
https://github.com/voltrue2/in-app-purchase/commit/41268a6a476d985a4522e245157821a42efe010f

I will be publishing the fixed version on npm as well.

**Comment by voltrue2** [comment]
I published v0.4.7 on npm. This should fix the issue we see.
It would be great, if you don't mind reporting back to me if it works or not.

Cheers

**Comment by anilalgoworks** [comment]
it still not working..
because in your setup method.. you arent checking for googlePublicKeyStrXXX yet
if (!config || !config.googlePublicKeyPath) {

		// try to read public key value from ENV if available
		// if this is set, reading the public key value from file system is ignored
		if (process.env[ENV_PUBLICKEY.SANDBOX]) {
			publicKeyMap.sandbox = process.env[ENV_PUBLICKEY.SANDBOX].replace(/s+$/, '');
		}
		if (process.env[ENV_PUBLICKEY.LIVE]) {
			publicKeyMap.live = process.env[ENV_PUBLICKEY.LIVE].replace(/s+$/, '');
		}

		// try to read public key value as string
		if (config && config.publicKeyStrSandbox) {
			publicKeyMap.sandbox = config.publicKeyStrSandbox;
		}
		if (config && config.publicKeyStrLive) {
			publicKeyMap.live = config.publicKeyStrLive;
		}

		// no google iap or we have the public key value from ENV variables
		return cb();
	}

**Comment by voltrue2** [comment]
// backward compatibility
        if (configIn && configIn.publicKeyStrSandbox) {
                config.publicKeyStrSandbox = configIn.publicKeyStrSandbox;
        }
        if (configIn && configIn.publicKeyStrLive) {
                config.publicKeyStrLive = configIn.publicKeyStrLive;
        }

This code above in .readConfig() should make sure that is reads publicKeyStrXXX configs.
Which version have you tried?

**Comment by anilalgoworks** [comment]
you got it right in config method .. but friend you have to put the same code in method just below it the setup method...

**Comment by voltrue2** [comment]
i think this should work since the code i pasted sets the values in .readConfig() as below
config.publicKeyStrSandbox = configIn.publicKeyStrSandbox;
config.publicKeyStrLive = configIn.publicKeyStrLive;

.setup() function will catch them. and if you look at test/google.js

I am testing both publicKeyXXXX and googlePublicKeyXXXX.

**Comment by anilalgoworks** [comment]
i just wanna say in validatePurchase we are getting key from publicKeyMap.xxx.

i just want to ask where are we setting googlePublicKeyXXXX to publicKeyMap.

if you can please try to test in same scenario then you will know the bug

**Comment by anilalgoworks** [comment]
i think it needs following code  

             if (config && config.googlePublicKeyStrSandbox) {
			publicKeyMap.sandbox = config.googlePublicKeyStrSandbox;
		}
		if (config && config.googlePublicKeyStrLive) {
			publicKeyMap.live = config.googlePublicKeyStrLive;
		}

before

             // no google iap or we have the public key value from ENV variables
		return cb();

**Comment by voltrue2** [comment]
yeah now that i look at the code a bit closer this seems off. thank you for sticking around for this issue. 
Let me change me test/google.js and look at the code right now.

**Comment by voltrue2** [comment]
ok the reason why my test/google.js was passing was because I was testing ENV var first and not resetting the values for the following tests.

**Comment by voltrue2** [comment]
OK I pushed the fix for this. I also needed to change the order of configuration check in .setup() for this.

**Comment by voltrue2** [comment]
f33098dc9941695821aea0e2c51f6e6e33f48c6a

**Comment by anilalgoworks** [comment]
thanks working fine now.

**Comment by voltrue2** [comment]
Great. Thank you for checking this. I really appreciate your help

On Tue, Apr 7, 2015 at 7:28 PM, voltrue2/in-app-purchase
<reply@reply.github.com>
wrote:thanks working fine now.

—
Reply to this email directly or view it on GitHub
[https://github.com/voltrue2/in-app-purchase/issues/7#issuecomment-90500230] .[https://github.com/notifications/beacon/ACKY4UfG8XDmfjNZ79j5gSCH8qEHsHTSks5n86jagaJpZM4D4ghW.gif]
